# 构建阶段
FROM openjdk:17-slim AS build
ENV HOME=/usr/app
RUN mkdir -p $HOME
WORKDIR $HOME
COPY . .
RUN chmod +x mvnw && \  # 添加执行权限
--mount=type=cache,target=/root/.m2 \
./mvnw -f pom.xml clean package  # 移除$HOME前缀（WORKDIR已设置）
  
  # 打包阶段
FROM openjdk:17-slim
WORKDIR /app
COPY --from=build /usr/app/target/*.jar ./app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "/app/app.jar"]  # 使用JSON格式